name: pull-request-build
run-name: "#${{ github.event.pull_request.number}} ${{ github.event.pull_request.title}}"
on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]


jobs:
  build-app:
    runs-on: "ubuntu-latest"
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      # Build preparations
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '25.0.4+101.0.LTS'
          distribution: temurin
          cache: gradle
      - uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699
        with:
          packages: platform-tools
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Install pebble SDK
        run: "uv tool install pebble-tool && pebble sdk install latest"
      - name: Compile library
        run: "./gradlew --parallel assemble"
      - name: Lint
        run: "./gradlew --continue --parallel lintDebug detektMain detektTest detektDebugUnitTest buildHealth reportMerge --continue"
      - name: Compile android kotlin sample
        run: "./gradlew --parallel assembleDebug"
        working-directory: sample/android
      - name: Compile android java sample
        run: "./gradlew --parallel assembleDebug"
        working-directory: sample/android-java
      - name: Compile pebble sample
        run: "pebble build"
        working-directory: sample/watch
